### ISSUE TITLE
README.md to start application incomplete

### ISSUE THREAD

**Issue by tranpeter** [clarkio/vulnerable-app#1]
When I executed gulp serve-dev on my environment I got a lot of errors due to missing packages. For someone that's not familiar with Node.js and the dependencies, he or she would be lost. It would be nice if you could provide the complete steps to execute before executing 'gulp serve-dev' such as npm install and bower install.

I'd recommend adding:

1. Open your terminal and cd to the root folder for this repository
2. Run npm install
3. Run bower install
4. Run gulp serve-dev to spin up the vulnerable-app
5. You should see your browser open up a new tab to the following URL: http://localhost:3000
6. Open a new terminal window or tab and cd to the /attacker-app folder from the root location of this repository
7. Run gulp serve-dev
8. You should see your browser open up another new tab to the following URL: http://localhost:3002

**Comment by clarkio** [comment]
Great suggestion. Those instructions are buried down in the latter half of the document so I agree it would be better to include them with the steps at the top. 

Would you like to create a PR with the changes?

**Comment by tranpeter** [comment]
Sure...will do.

**Comment by clarkio** [comment]
Fixed in #2. Thanks again for the helpful contributions!
