### ISSUE TITLE
App craching

### ISSUE THREAD

**Issue by wefahakem** [clarkio/vulnerable-app#3]
I'm trying to run the app. But when I run gulp serve-dev I'm getting : 
[nodemon] app crashed - waiting for file changes before starting...
What can be the pb?

**Comment by jabney** [comment]
I had an issue with the app hanging. It was resolved for me by changing `gulpfile.js` line 433 from:

var debugMode = '--debug';

to:

var debugMode = '--inspect';

**Comment by clarkio** [comment]
Hey, thanks for this feedback @wefahakem and @jabney. Sorry for the delay on getting back to you both on this. Seems @jabney's solution will help and I'll update the gulpfile to reflect that (since node debug flag has changed)

**Comment by clarkio** [comment]
Fixed in #4

**Comment by jabney** [comment]
@clarkio, yeah it was a node version thing. i was running node `v8.9.x`. Note, if I'm not mistaken the fix may cause issues for those running the version recommended in the readme, `v6.11.x`.

**Comment by clarkio** [comment]
Ah, good point @jabney I'll take a look and see if we just upgrade everything to `v8.9.x`
